-- Auto-generated by matugen — Material You accents for Hyprland.
-- Require with: local colors = require("colors")

local M = {}

M.mat_primary           = "rgba(d9c76fcc)"
M.mat_primary_container = "rgba(524600cc)"
M.mat_secondary         = "rgba(d0c6a2cc)"
M.mat_tertiary          = "rgba(a9d0b4cc)"
M.mat_surface           = "rgba(15130baa)"
M.mat_surface_variant   = "rgba(4a4739aa)"
M.mat_outline           = "rgba(969080aa)"
M.mat_shadow            = "rgba(000000ee)"

return M
